### ISSUE TITLE
The ecosystem, community size is missing (and is important for this kind of choice to be futur-proof)

### ISSUE THREAD

**Issue by FGRibreau** [KaivoAnastetiks/container-orchestration-comparison#3]
- Kubernetes ( 1K+ contributors, 7122 forks...)
- Docker swarm (161 contributors, 889 forks...)
- Nomad (142 contributos, 398 forks...)
- ...

**Comment by GuillaumeRochat** [comment]
Hi @FGRibreau, aside from number of contributors and forks, do you think there are other valuable metrics to include to determine the community size?

**Comment by FGRibreau** [comment]
Hum, Google trend would give a trend but I'm not sure it would be really relevant.
The documentation size could also be added but again it's hard to quantify :)

**Comment by GuillaumeRochat** [comment]
@FGRibreau I added the Stars, Forks and Contributors of the respective github repositories. I agree that Google trend would probably not be that relevant. For instance, Nomad would most likely not be referencing the Nomad tool.

**Comment by FGRibreau** [comment]
Indeed, perfect addition, thanks @KaivoAnastetiks!
